apiVersion: v1
kind: Secret
metadata:
  name: cosmos-secret
type: Opaque
stringData:
  POSTGRES_PASSWORD: xenna
  DATABASE_URL: postgresql+psycopg2://xenna:xenna@postgres:5432/xenna_management
  SECRET_KEY: replace-with-random-secret
  SECRET_ENCRYPTION_KEY: cuWRV_El44bUKXOBlIqg1uDM7mtgXAQQizK1tvkKF1c=
  DEFAULT_ADMIN_PASSWORD: Admin123!
  DEFAULT_DEV_PASSWORD: Dev123!
  DEFAULT_AIOPS_PASSWORD: Aiops123!
